# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.

defaults: &defaults
  database_config_path: 'config/database.yml'
  log_path: 'log/<%= Rails.env %>.log'
  auth_username: cc

  services:
  - name: p-mysql
    id: 3101b971-1044-4816-a7ac-9ded2e028079
    description: MySQL service for application development and testing
    tags:
      - mysql
      - relational
    max_db_per_node: 5
    metadata:
      displayName: "Pivotal MySQL Dev"
      imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAABMCAYAAADJEu0BAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyNpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOToxNSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjBDOTlBMkE3NDQ3MDExRTNCN0I5RDc0MjE2NTBCMjgzIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjBDOTlBMkE4NDQ3MDExRTNCN0I5RDc0MjE2NTBCMjgzIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6MEM5OUEyQTU0NDcwMTFFM0I3QjlENzQyMTY1MEIyODMiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6MEM5OUEyQTY0NDcwMTFFM0I3QjlENzQyMTY1MEIyODMiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz7RmE0vAAAGn0lEQVR42uycTYgjRRTH38heFNTJiFdlO3rx2nMQQXbADAwePAg94ElByJxW0Eui4HmSo3OQ3RZkERFMHwTxIpODtznMNLuuKIim/dZZD7b4wXrZjZ3wauZtWZ2uTqfjJP3/QTGTTnem+tW/Xr33uiYr1L44pBIZ7u6tEAAlcxdMACBkACBkACBkACBksHycyzrh9ae2aO3ue05exzdv0sEP39L+118S3b4NC4LFEPKL64/Tw6tr/zn+6fHPtPH2m/T7n3/AiuDsC1mxdeUS3fj7L3ro/lV6+YkLtOE8Sm9sPUPPB+/CimBxYuTrvx7TtR+/pw8/v07Pvv/O+NiT5+uwIECyB8DcQ4sRq/feR4898CC9dqExfv1J9BUsCBZPyB889wJtnH9k/PthEma88vFHsCBYPCG/dXhAvc+u0rVffqKD774hGg5hQbB4Qn7v6iEsBpDsAQAhA1AktPjixvH4sfQ/t27BWmBxhfz0lUuwEkBoAQCEDACEDCBkACBkAObPyhCPmQE8MgAQMgAQMgAQMli+ZI/aF0c/vaS5SYuT1s1xvbpuRLtgX2pJayZt9O8njjgeJK3PbRINbp523OfPiDKub3Efit6H+hydmPsQzHIAh7t7ULEQck8IYNNCNIqBEF2Rb910uQ8OD3gsxK1EEXLfYsMEuCz6H2nv1YSg24br9Xsp+u2hA20imgTd575EEPJsQwtXHGtaXtsQwivqifeFNxx9iUad2xqLN+D3Y8ME2GcRB3xuXbt+mydBU/ydebBtaF2+h1F/j3LYGmQgd79FbOSG5bVqEPqG5TwPTSFiU1ijwopaiid2J1yrQpOAz1ViXp+DbYOUY23uR4f7VMsZzgGLZE95vpalR+7PYHlsTBh4fUnWY1GXRWAjhB3+G67l/ZWJL8KklsUq4RR0FpUUMll4ZWV8Uyzds4gTG3xOS4uH8yaGcc7krJszfCqTkPtTY+9sosN2GrBdh/zzxFYrr77US9ogaan2Tt5r8DmtqghZZdUNLW42CVGvcDhigLI8iMfnRHw+iWXWtlpSm6ICEPLkc3KEUGUiY2Z9oh6Jia5WnUDE17Up7V0JIZPwst6ECkPDICJXLJtxhtfzxKTp8mC4YvBslloSkyCvmCljos6TmO9X9kfG/uv8s80JY5vvv5XD3qPxioa7e0GVhOyzyLwpY9o4w+up5M4Xxzb5tcPL6W+clKWJ2k2Jm22Ipghl5pEUOuLePDHJ08Kj8fgk4jyxdxI6eIawosmf7VchRnYMxk1brppiiZ6UzKTFop5hIsScjNXZ44Q8CToiljZ55Gk94FnGs0h+I20i+hNWUdtkeuk8srxpz2AUx8IofSHGmiZAFZZEKQPU5eW0LgZIlaqoQEgxi0lQBk6KkGWip7c7auqJVz6xd+KBZSKonFGQnBNVUcghN08zdDPH7A5EdUEfJJsnhxF76XX+vSm8S1hAlM4MJkMZQg4ybCmbbwgVitp7KYWc5pXz1I59Q0aukrw88Zo8XxfyNLVVVXE5C0uty80kNPmEsm1oXYvx8jjJ86ssZF2IrZwlL5WEuFqbRkBRSuji5hRziz3gWfFQLYPHDLVJawWHDuMHPklIMW4F7L1UQtaFqDyZnyP2lElInrAk7bNjQ/besaxAqCd6eR+ilIXa6BRq3jWckCjbVkCalkljJYRMWrLVSDHKpCdzfRFrN8Rr3Su1LAXoa4PWZZHvU/YDAbkx6f9MfEYiOxLVn03t/a6wWZpdaiZ7c504otPtrP3kWFgFIZ/LKM/0hWHSzoksvERH86K6yFweWCX0WCyvnhCgXjpTx0af36PTDUaR8ORyr/WORXw+sKjI7FjYdpCxak3aVrrDE6/DfQ/ptOSmwql2yr34GfZeWiFnLcvKMFm14ywhpyV5m+x5vJTlNOSBTfMs6tHtZTrdXG8S3zbZ1ZCzKiG2satjWLkiUXWY5ABCrtZ02C5eSlVpkr3jKiR5CrWxvuzM/IgHb8di8F1twPKEATVNaMrT10Qsumgxo35Pfbqzhkwg5zfWF4gJiexKblHB+FUvq6k4usX96C2goGOqSMJWZrI3C7yMpXAeQlCbb9R+5B6vEgBCtiJv7blMIo6T62T3z6igwqGFJ+JaVT6Kzlj2rAQNIOSJ8XBDW9YhGrBwQvbptJjfZ0+MJRyUDr6NEyDZAwBCBgBCBgBCBhAyABAyABAyABAygJABgJABgJABgJABhAwAhAwAhAwAhAwgZAAgZAAgZAAgZAAgZLBc/CvAALNW7XVv+EUjAAAAAElFTkSuQmCC"
      longDescription: "A MySQL relational database service for development and testing. The MySQL server is multi-tenant and is not replicated."
      providerDisplayName: "Pivotal Software"
      documentationUrl:
      supportUrl: "http://support.cloudfoundry.com/"
    plans:
    - name: 5mb
      id: 2451fa22-df16-4c10-ba6e-1f682d3dcdc9
      description: Free Trial
      max_storage_mb: 5
      metadata:
        costs:
        - amount:
            usd: 0.0
          unit: MONTHLY

        bullets:
          - Shared MySQL server
          - 5 MB storage
          - 40 concurrent connections

development:
  auth_password: 'secret'
  <<: *defaults

test:
  auth_password: 'secret'
  <<: *defaults
